### ISSUE TITLE
Compatibilidad de versiones SLPS-01797 Ok SLPS-91233 No funciona

### ISSUE THREAD

**Issue by Jrublgo** [uzuhenry/DW-ESP-retranslation#2]
Buenas. He comprobado que la version normal del juego (SLPS-01797) va correctamente en los emuladores indicados. No obstante, la version "blanca" tambien conocida como greatest hits (SLPS-91233) parece no sacar ningún iso con el parche aplicado.

Simplemente por indicar si a esta última se le va a ofrecer soporte o no. 

Gracias.

**Comment by uzuhenry** [comment]
Los cambios, de la versión 1.0 a la 1.1 ( la de playstation the best) son fundamentalmente diferentes en muchos aspectos de código. Y esa versión es bastante más difícil de conseguir hoy en día que la 1.0, Así que no creo que tenga soporte.

Igualmente, el parche aplica casi todas las correcciones de la 1.1 (excepto las que añaden bugs nuevos), así que no os perdéis nada.

Dicho esto, es cierto que debería especificar en el readme que sólo funciona con 1.0, muchas gracias por tu atención!
