### ISSUE TITLE
Error cambio de carta Clearagumon - Toy Town

### ISSUE THREAD

**Issue by Miloren1** [uzuhenry/DW-ESP-retranslation#3]
El problema radica que en la traducción Clearagumon dice que quiere una carta de Waruseadramon cuando en realidad debiera ser Warumonzaemon.

![SLPS-01797_2023-12-08_01-23-36](https://github.com/uzuhenry/DW-ESP-retranslation/assets/20927482/01ed59b1-f798-4f47-b71d-d622839a02ba)

**Comment by uzuhenry** [comment]
Queda anotado como corrección para la siguiente revisión. Gracias por el aviso.
