### ISSUE TITLE
Mojyamon adicional aparece en la pantalla cuando cambiamos un item reiteradas veces

### ISSUE THREAD

**Issue by Miloren1** [uzuhenry/DW-ESP-retranslation#4]
Aparece un Mojyamon extra en pantalla cuando cambiamos items reiteradas veces con el Mojyamon de la pantalla de abajo de Tierra Congelada (la que tiene 2 Mojyamon, el de la izquierda).

Este pudiera ser un error de la versión japonesa en general y no de la versión parcheada, no estoy seguro porque tampoco he jugado la versión NTSC J demasiado.

![SLPS-01797_2023-12-02_00-35-44](https://github.com/uzuhenry/DW-ESP-retranslation/assets/20927482/a8f3e61d-bcd0-4d02-8801-742bbb66abd8)

**Comment by uzuhenry** [comment]
Este es un bug común a todas las versiones del juego. Cuando completas el mojyamon de la derecha, empieza a bailar, su animación de baile no está bien calibrada así que cada loop el personaje se desplaza un poco. Si esperamos / interactuamos con el otro durante cierto tiempo este mojyamon se desplazará tanto que hasta puede verse desde donde no debería.
