### ISSUE TITLE
Icedevimon/Hyogamon caminando contra una piedra en lugar de deambular

### ISSUE THREAD

**Issue by Miloren1** [uzuhenry/DW-ESP-retranslation#5]
En la pantalla de tierra congelada previa a llegar a la casa de penguinmon (la que tiene un roca en el centro), tanto Hyogamon/Icedevimon de la izquierda quedan caminando contra una piedra trabados en lugar de deambular como debieran hacerlo. Esto se soluciona si el jugador se acerca lo suficiente al digimon.

Este podría ser un error de la versión japonesa y no del parche en sí.

![SLPS-01797_2023-11-26_03-59-04](https://github.com/uzuhenry/DW-ESP-retranslation/assets/20927482/3bdb591a-413e-46ef-98cb-05c32b0660bd)

**Comment by uzuhenry** [comment]
Uno de los puntos de ruta está situado dentro de esa roca, es un pequeño despiste de la versión original.
