### ISSUE TITLE
parche 1.3me marca error

### ISSUE THREAD

**Issue by philionel** [uzuhenry/DW-ESP-retranslation#6]
hola trate de parchar el juego iso japones con el parche 1.3 pero me marca error me saca este mensaje, tambien lo he intentado sin poner cosas random pero sale igual, no se si falta algo de descargar o si puedes parchar una vercion random y normal tu de la 1.3,saca este mensaje
version modificando parametros
![error parche](https://github.com/uzuhenry/DW-ESP-retranslation/assets/172483064/45b9e43a-6761-40bf-8e65-f37de6e42ff7)
saca este mensaje
versión sin modificar nada 
![error parche dos](https://github.com/uzuhenry/DW-ESP-retranslation/assets/172483064/456047bd-c4d1-4f5e-93d6-2aef2913ef17)

**Comment by uzuhenry** [comment]
Ese error es porque no estás usando una imagen correcta, comprueba el md5 con el indicado en el readme.

**Comment by philionel** [comment]
pues yo uso el archivo de la pagina https://cdromance.org/psx-iso/digimon-world-japan/ pero me sigue marcando error y uno ultraiso para convertirlo en formato .iso
